// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as HistoryCmp from "./HistoryCmp.res.mjs";
import * as Caml_format from "rescript/lib/es6/caml_format.js";
import * as IncomeExpenseCmp from "./IncomeExpenseCmp.res.mjs";
import * as BalanceTrackerCmp from "./BalanceTrackerCmp.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function AddNewTransactionCmp(props) {
  var match = React.useState(function () {
        return [];
      });
  var setTransaction = match[1];
  var transaction = match[0];
  React.useEffect((function () {
          localStorage.getItem("transactions");
        }), []);
  React.useEffect((function () {
          if (transaction.length > 0) {
            var jsonArray = Belt_Array.map(transaction, (function (element) {
                    return {};
                  }));
            localStorage.setItem("transactions", JSON.stringify(jsonArray));
          }
          
        }), [transaction]);
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(BalanceTrackerCmp.make, {
                      props: transaction
                    }),
                JsxRuntime.jsx(IncomeExpenseCmp.make, {
                      props: transaction
                    }),
                JsxRuntime.jsxs("form", {
                      children: [
                        JsxRuntime.jsx("h4", {
                              children: "Add New Transaction"
                            }),
                        JsxRuntime.jsx("label", {
                              children: "Text"
                            }),
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx("input", {
                              id: "note",
                              placeholder: "Enter Text...",
                              type: "text"
                            }),
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx("label", {
                              children: "Amount"
                            }),
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx("input", {
                              id: "amount",
                              placeholder: "Enter Amount...",
                              type: "number"
                            }),
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx("br", {}),
                        JsxRuntime.jsx("button", {
                              children: "Add Transaction",
                              id: "transaction-btn",
                              type: "submit"
                            })
                      ],
                      className: "input-details",
                      onSubmit: (function (e) {
                          e.preventDefault();
                          var newNote = e.target.note.value;
                          var newAmount = Caml_format.int_of_string(e.target.amount.value);
                          var newTransaction = {
                            note: newNote,
                            amount: newAmount
                          };
                          setTransaction(function (prev) {
                                return Js_array.concat(prev, [newTransaction]);
                              });
                        })
                    }),
                JsxRuntime.jsx(HistoryCmp.make, {
                      props: transaction
                    })
              ]
            });
}

var make = AddNewTransactionCmp;

export {
  make ,
}
/* react Not a pure module */
