// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function BalanceTrackerCmp(props) {
  var totalSum = Belt_Array.reduce(props.props, 0, (function (acc, t) {
          return acc + t.amount | 0;
        }));
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("p", {
                    children: [
                      JsxRuntime.jsx("h4", {
                            children: "Your Balance"
                          }),
                      JsxRuntime.jsx("h1", {
                            children: "$" + totalSum.toString()
                          })
                    ]
                  }),
              className: "balance"
            });
}

var make = BalanceTrackerCmp;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
