// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function HistoryCmp(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h4", {
                      children: "History"
                    }),
                Belt_Array.mapWithIndex(props.props, (function (index, transaction) {
                        return JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("p", {
                                            children: transaction.note
                                          }),
                                      JsxRuntime.jsx("p", {
                                            children: "$" + String(transaction.amount)
                                          })
                                    ],
                                    className: "history-elements " + (
                                      transaction.amount > 0 ? "income" : "expense"
                                    )
                                  }, String(index));
                      }))
              ],
              className: "history"
            });
}

var make = HistoryCmp;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
