// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function IncomeExpenseCmp(props) {
  var match = Belt_Array.reduce(props.props, [
        0,
        0
      ], (function (param, t) {
          var e = param[1];
          var i = param[0];
          if (t.amount > 0) {
            return [
                    i + t.amount | 0,
                    e
                  ];
          } else {
            return [
                    i,
                    e + t.amount | 0
                  ];
          }
        }));
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                              children: "Income"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "$" + match[0].toString()
                            })
                      ],
                      className: "income-expense-cell",
                      id: "income"
                    }),
                JsxRuntime.jsx("div", {
                      className: "income-expense-divider"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("p", {
                              children: "Expenses"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "$" + (-match[1] | 0).toString()
                            })
                      ],
                      className: "income-expense-cell",
                      id: "expense"
                    })
              ],
              className: "income-expense"
            });
}

var make = IncomeExpenseCmp;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
