// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as AddNewTransactionCmp from "./components/AddNewTransactionCmp.res.mjs";

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Expense Tracker"
                    }),
                JsxRuntime.jsx(AddNewTransactionCmp.make, {})
              ],
              className: "app-container"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
